service: swing-notes
frameworkVersion: '3'

useDotenv: true

provider:
  name: aws
  runtime: nodejs18.x
  region: eu-north-1
  httpApi:
    cors: true
  iam:
    role: arn:aws:iam::964128208950:role/school
  deploymentMethod: direct
  environment:
    TABLE_NAME: swing-notes
    JWT_SECRET: ${env:JWT_SECRET}

plugins:
  - serverless-webpack

package:
  individually: true

functions:
  loginUser:
    handler: src/functions/user/loginUser.handler
    events:
      - httpApi:
          path: /api/user/login
          method: POST
  registerUser:
    handler: src/functions/user/registerUser.handler
    events:
      - httpApi:
          path: /api/user/register
          method: POST
  getAllNotes:
    handler: src/functions/notes/getAllNotes.handler
    events:
      - httpApi:
          path: /api/notes
          method: GET
  createNote:
    handler: src/functions/notes/createNote.handler
    events:
      - httpApi:
          path: /api/notes
          method: POST
  updateNote:
    handler: src/functions/notes/updateNote.handler
    events:
      - httpApi:
          path: /api/notes/{noteId}
          method: PUT
  deleteNote:
    handler: src/functions/notes/deleteNote.handler
    events:
      - httpApi:
          path: /api/notes/{noteId}
          method: DELETE

resources:
  Resources:
    Events:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.TABLE_NAME}
        AttributeDefinitions:
          - AttributeName: PK
            AttributeType: S
          - AttributeName: SK
            AttributeType: S
          - AttributeName: username
            AttributeType: S
        KeySchema:
          - AttributeName: PK
            KeyType: HASH
          - AttributeName: SK
            KeyType: RANGE
        GlobalSecondaryIndexes:
          - IndexName: usernames
            KeySchema:
              - AttributeName: username
                KeyType: HASH
            Projection:
              ProjectionType: ALL
        BillingMode: PAY_PER_REQUEST
