service: where-its-at-dynamodb
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: eu-north-1
  httpApi:
    cors: true
  iam:
    role: arn:aws:iam::964128208950:role/school
  deploymentMethod: direct

plugins:
  - serverless-webpack

package:
  individually: true

functions:
  getEvents:
    handler: functions/getEvents.handler
    events:
      - httpApi:
          path: /events
          method: GET

  buyTicket:
    handler: functions/buyTicket.handler
    events:
      - httpApi:
          path: /tickets/{eventId}
          method: POST

  verifyTicket:
    handler: functions/verifyTicket.handler
    events:
      - httpApi:
          path: /staff/verify
          method: POST

resources:
  Resources:
    Events:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: events
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: 'N'
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST

    Tickets:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: tickets
        AttributeDefinitions:
          - AttributeName: number
            AttributeType: S
        KeySchema:
          - AttributeName: number
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
